// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUoXv_343lW_T9HQAB4gJvGuHXDPQGvaQ',
    appId: '1:1013165597659:web:83db7bdc219d9520defdfe',
    messagingSenderId: '1013165597659',
    projectId: 'diapp0227-c7c1e',
    authDomain: 'diapp0227-c7c1e.firebaseapp.com',
    databaseURL: 'https://diapp0227-c7c1e-default-rtdb.firebaseio.com',
    storageBucket: 'diapp0227-c7c1e.appspot.com',
    measurementId: 'G-JHWX5Y1CYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVvWb5GhFJjxKtOwMju3UuCFOARcX7uX8',
    appId: '1:1013165597659:android:0ca6748faf3ebb3fdefdfe',
    messagingSenderId: '1013165597659',
    projectId: 'diapp0227-c7c1e',
    databaseURL: 'https://diapp0227-c7c1e-default-rtdb.firebaseio.com',
    storageBucket: 'diapp0227-c7c1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvqeFb4q4I2QgeNYBKsv6eRkILx4ge3wQ',
    appId: '1:1013165597659:ios:e8f2f00fe6c2956ddefdfe',
    messagingSenderId: '1013165597659',
    projectId: 'diapp0227-c7c1e',
    databaseURL: 'https://diapp0227-c7c1e-default-rtdb.firebaseio.com',
    storageBucket: 'diapp0227-c7c1e.appspot.com',
    iosBundleId: 'com.example.diapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvqeFb4q4I2QgeNYBKsv6eRkILx4ge3wQ',
    appId: '1:1013165597659:ios:7858919a7382f0a4defdfe',
    messagingSenderId: '1013165597659',
    projectId: 'diapp0227-c7c1e',
    databaseURL: 'https://diapp0227-c7c1e-default-rtdb.firebaseio.com',
    storageBucket: 'diapp0227-c7c1e.appspot.com',
    iosBundleId: 'com.example.diapp.RunnerTests',
  );
}
